# Generated by Django 3.2.16 on 2022-12-23 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_total_investment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_investment',
        ),
    ]
